### ISSUE TITLE
Implement API authentication

### ISSUE THREAD

**Issue by adhikasp** [blibli-future/detroit#8]
For simplicity, I think we can just use basic HTTP auth.

Tutorial I found from a 10 sec google search:
http://www.baeldung.com/spring-security-basic-authentication

**Comment by DitoRaharjo** [comment]
Nice, let me learn it for a while, then we can try to implement it.

**Comment by adhikasp** [comment]
@kabal86 What is your opinion about this?

**Comment by yogiehartanto** [comment]
@adhikasp it's different with http://www.baeldung.com/how-to-use-resttemplate-with-basic-authentication-in-spring ?
